Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -46,9 +46,41 @@ jobs:
           name: nekoray_arm64
           path: nekoray/build/nekoray_arm64.zip
 
+  test:
+    strategy:
+      matrix:
+        os: [macos-10.15]
+        arch: [amd64]
+
+    runs-on: ${{ matrix.os }}
+    needs: build
+
+    steps:
+      - name: Download Artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: nekoray_${{ matrix.arch }}
+          path: ./
+
+      - name: Unzip Artifact
+        run: |
+          unzip -q nekoray_${{ matrix.arch }}.zip
+          mv nekoray_${{ matrix.arch }}.app nekoray.app
+
+      - name: Run Nekoray
+        run: |
+          ./nekoray.app/Contents/MacOS/nekoray > nekoray.log 2>&1 &
+          nekoray_pid=$!
+          sleep 10
+          if ! ps -p "$nekoray_pid" > /dev/null; then
+            echo "Nekoray failed to stay open for 10 seconds."
+            cat nekoray.log
+            exit 1
+          fi
+
   create_release:
     runs-on: ubuntu-latest
-    needs: build
+    needs: test
     permissions:
       contents: write
       packages: write
